{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "irembo-node.serviceAccountName" . }}
  labels:
{{ include "irembo-node.labels" . | nindent 4 }}
{{- end -}}
